# Generated by Django 4.1.7 on 2023-05-31 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_my_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='my_user',
            table='my_User',
        ),
    ]
