# Generated by Django 4.1.7 on 2023-05-31 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='dish',
            table='Dish',
        ),
    ]
